-- Seeds the same demo account the old mock-data version hardcoded, so local dev and the
-- demo login flow keep working after moving to a real database. password_hash/password_salt
-- below are a PBKDF2 hash of "admin123" generated by scripts/hash-demo-password.ts — see
-- that script if you need to regenerate this for a different password.
INSERT INTO users (id, email, name, password_hash, password_salt)
VALUES (
  'demo-user-1',
  'admin@flowfunds.com',
  'Admin User',
  'e34257e69a701ec11f4d308d2cc564c66c987bfee5f9fd151aae6277b5bda225',
  'ab90f94c3164104b87360537fe2db84f'
);

INSERT INTO budgets (id, user_id, name, category, monthly_limit) VALUES
  ('budget-dining', 'demo-user-1', 'Dining', 'dining', 500),
  ('budget-groceries', 'demo-user-1', 'Groceries', 'groceries', 800),
  ('budget-transportation', 'demo-user-1', 'Transportation', 'transportation', 300);

INSERT INTO transactions (id, user_id, amount, merchant, category, date) VALUES
  ('txn-seed-1', 'demo-user-1', 25.50, 'Coffee Shop', 'dining', '2024-01-15'),
  ('txn-seed-2', 'demo-user-1', 120.00, 'Grocery Store', 'groceries', '2024-01-14'),
  ('txn-seed-3', 'demo-user-1', 50.00, 'Gas Station', 'transportation', '2024-01-13'),
  ('txn-seed-4', 'demo-user-1', 131.25, 'Grocery Store', 'groceries', '2024-01-20'),
  ('txn-seed-5', 'demo-user-1', 369.00, 'Metro Transit', 'transportation', '2024-01-22');
